# Generated by Django 2.2.3 on 2019-08-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientsite', '0002_auto_20190731_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('questioner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='question/facts/images/')),
                ('quest', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(blank=True, max_length=500, null=True)),
                ('doctor', models.ManyToManyField(related_name='whoanswered', to='clientsite.User')),
                ('quest', models.ManyToManyField(related_name='question', to='qusans.Question')),
            ],
        ),
    ]
