# Generated by Django 2.2.3 on 2019-08-01 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientsite', '0002_auto_20190731_0130'),
        ('qusans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='appreciation',
            field=models.ManyToManyField(blank=True, related_name='accepted', to='clientsite.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
